### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by eqvpkbz** [Schwarzkopf-Henkal/Chat-Room-Lite#22]
使用markdown时， 使用代码块， 在代码块中的尖括号全部变为html中显示该字符对应的字符方式， 但是并没有正确显示

显示 :

```cpp
&lt; &gt;
```

而不是

```cpp
<>
```

然后有消息时进度条自动下拉这个功能好像不见了， 希望修复

**Comment by tiger2005** [comment]
已经修复。谢谢你的支持！
