### ISSUE TITLE
新特性

### ISSUE THREAD

**Issue by eqvpkbz** [Schwarzkopf-Henkal/Chat-Room-Lite#24]
希望添加的内容:

-  输入框内支持tab
- 支持自添加服务器地址和端口， 点击服务器地址前面的图标直接跳到输入名字环节

**Comment by Schwarzkopf-Henkal** [comment]
感谢反馈！第一个大概马上就能修，第二个的话会加入代办事项的，（也许）会添加一个能支持快速导入自定义服务器的方法。

**Comment by Schwarzkopf-Henkal** [comment]
第一个好像出了点问题（
Tab键默认被浏览器拦截下来了，我这边JS连keypress事件都没有（

**Comment by eqvpkbz** [comment]
希望添加: 

- 房间的备注(用来描述聊天室规则或者特点)

**Comment by eqvpkbz** [comment]
@Schwarzkopf-Henkal

**Comment by eqvpkbz** [comment]
希望添加: 

- 浏览器PWA应用支持(如OI-wiki的应用添加功能)

**Comment by eqvpkbz** [comment]
@Schwarzkopf-Henkal

**Comment by Schwarzkopf-Henkal** [comment]
> 希望添加:
> 
> * 浏览器PWA应用支持(如OI-wiki的应用添加功能)

将会加入展望，目前不清楚这个东西具体是怎么搞，所以也许会研究一下看看是不是合适实现

当然，现在这个网页布局响应式等于0，转成那种样子可能会遇见奇奇怪怪的兼容性问题，网页布局大概也要改吧

**Comment by tiger2005** [comment]
剩余问题: PWA 兼容已经另开 issue。
