### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by eqvpkbz** [Schwarzkopf-Henkal/Chat-Room-Lite#25]
```
 Error Code : 1006
Cannot find the service.
```

在服务端的电脑上， 当我一段时间不发消息， 就会自动连不到设备

DEVICE INFO:

```
OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.4.0-56-generic
CPU: AMD PRO A10-8770 R7, 10 COMPUTE CORES 4C+6G @ 4x 3.5GHz
GPU: AMD/ATI Oland [Radeon HD 8570 / R7 240/340 / Radeon 520 OEM]
RAM: 3229MiB / 3927MiB
```

我猜测这是否是因为我中间将电脑锁屏导致的， 但是我锁屏后别的聊天室的成员却没有发生任何事， 这让我感到困惑

**Comment by eqvpkbz** [comment]
不锁屏也在一段时间之后连接不到设备了QAQ

**Comment by Schwarzkopf-Henkal** [comment]
@eqvpkbz 话说这电脑配置有点熟悉啊（

是指启动服务端的那台电脑，使用客户端登录到服务器之后一段时间不发消息自动掉线吗？登录到服务端的时候使用的是localhost还是内网IP？如果只是用其中一个的话，试试看换另一种登录方式是否会出现这个问题？

**Comment by eqvpkbz** [comment]
@Schwarzkopf-Henkal  服务端有时候会报这样的错误: 

```
Version 9 of Highlight.js has reached EOL and is no longer supported.
Please upgrade or ask whatever dependency you are using to upgrade.
https://github.com/highlightjs/highlight.js/issues/2877
KaTeX auto-render: Failed to parse `2^2^2` with  { ParseError: KaTeX parse error: Double superscript at position 4: 2^2^̲2
    at new ParseError (/home/eqvpkbz/node_modules/katex/dist/katex.js:261:14)
    at Parser.parseAtom (/home/eqvpkbz/node_modules/katex/dist/katex.js:16418:17)
    at Parser.parseExpression (/home/eqvpkbz/node_modules/katex/dist/katex.js:16243:23)
    at Parser.parse (/home/eqvpkbz/node_modules/katex/dist/katex.js:16211:22)
    at parseTree (/home/eqvpkbz/node_modules/katex/dist/katex.js:17195:21)
    at renderToDomTree (/home/eqvpkbz/node_modules/katex/dist/katex.js:17302:16)
    at Object.render (/home/eqvpkbz/node_modules/katex/dist/katex.js:17242:14)
    at renderMathInText (/home/eqvpkbz/node_modules/katex/dist/contrib/auto-render.js:249:34)
    at renderElem (/home/eqvpkbz/node_modules/katex/dist/contrib/auto-render.js:273:18)
    at /home/eqvpkbz/node_modules/katex/dist/contrib/auto-render.js:285:11 name: 'ParseError', position: 3 }
```

**Comment by eqvpkbz** [comment]
> @eqvpkbz 话说这电脑配置有点熟悉啊（
> 
> 是指启动服务端的那台电脑，使用客户端登录到服务器之后一段时间不发消息自动掉线吗？登录到服务端的时候使用的是localhost还是内网IP？如果只是用其中一个的话，试试看换另一种登录方式是否会出现这个问题？

是的， 登陆用的是index.html， 用内网ip来登录的， 请问怎么用localhost 登陆呢？

**Comment by Schwarzkopf-Henkal** [comment]
> > @eqvpkbz 话说这电脑配置有点熟悉啊（
> > 是指启动服务端的那台电脑，使用客户端登录到服务器之后一段时间不发消息自动掉线吗？登录到服务端的时候使用的是localhost还是内网IP？如果只是用其中一个的话，试试看换另一种登录方式是否会出现这个问题？
> 
> 是的， 登陆用的是index.html， 用内网ip来登录的， 请问怎么用localhost 登陆呢？

应该是只要把内网IP替换成localhost就行了吧：

![](https://cdn-warfare-1302619124.file.myqcloud.com/Bug_or_Feature.png)

**Comment by eqvpkbz** [comment]
好的， 谢谢

**Comment by tiger2005** [comment]
> @Schwarzkopf-Henkal 服务端有时候会报这样的错误:
> 
> ```
> Version 9 of Highlight.js has reached EOL and is no longer supported.
> Please upgrade or ask whatever dependency you are using to upgrade.
> https://github.com/highlightjs/highlight.js/issues/2877
> KaTeX auto-render: Failed to parse `2^2^2` with  { ParseError: KaTeX parse error: Double superscript at position 4: 2^2^̲2
>     at new ParseError (/home/eqvpkbz/node_modules/katex/dist/katex.js:261:14)
>     at Parser.parseAtom (/home/eqvpkbz/node_modules/katex/dist/katex.js:16418:17)
>     at Parser.parseExpression (/home/eqvpkbz/node_modules/katex/dist/katex.js:16243:23)
>     at Parser.parse (/home/eqvpkbz/node_modules/katex/dist/katex.js:16211:22)
>     at parseTree (/home/eqvpkbz/node_modules/katex/dist/katex.js:17195:21)
>     at renderToDomTree (/home/eqvpkbz/node_modules/katex/dist/katex.js:17302:16)
>     at Object.render (/home/eqvpkbz/node_modules/katex/dist/katex.js:17242:14)
>     at renderMathInText (/home/eqvpkbz/node_modules/katex/dist/contrib/auto-render.js:249:34)
>     at renderElem (/home/eqvpkbz/node_modules/katex/dist/contrib/auto-render.js:273:18)
>     at /home/eqvpkbz/node_modules/katex/dist/contrib/auto-render.js:285:11 name: 'ParseError', position: 3 }
> ```

这个是 highlight.js 和 showdown-hoghlight 的问题。请在使用代码块的时候尽量将五央视代码块加入 plain 样式，或者在服务器端使用 `npm` 安装 `highlight.js` 以解决问题。
