### ISSUE TITLE
主题设置

### ISSUE THREAD

**Issue by eqvpkbz** [Schwarzkopf-Henkal/Chat-Room-Lite#40]
希望能够加入更多的颜色主题， 处理更多的细节(比如light主题中的`inline-block`的主题颜色好丑)

希望能够自主设置`hljs`的配色（还是仿照[hack.chat](https://hack.chat/) ）

**Comment by tiger2005** [comment]
前者已经进行更改。后者问题将合并到主题商店等问题中。
