### ISSUE TITLE
连接问题

### ISSUE THREAD

**Issue by xiaomai-github-studio** [Schwarzkopf-Henkal/Chat-Room-Lite#51]
我今天使用时发现每个连接都是断开的，请问是怎么回事
![page](https://user-images.githubusercontent.com/63173873/109373429-a40d9a00-78e9-11eb-98be-5e57a9578cee.png)

**Comment by Schwarzkopf-Henkal** [comment]
这个东西的本意是叫你们在机房里自己搭服务器自己用，之前我自己提供的服务器重启之后就没再上线了，现在会启动
