### ISSUE TITLE
未认证用户也能接受，发送，显示动态用户列表

### ISSUE THREAD

**Issue by Schwarzkopf-Henkal** [Schwarzkopf-Henkal/Chat-Room-Lite#7]
在输入IP和端口，建立连接之后，能够直接发送信息，接受房间内人的信息，显示动态用户列表。用户名显示undefined。

话说写码的质量要提高点啊……不能随便就加一个游离的请求种类，新功能加爽了，bug倒是顾头不顾尾地冒出来了……

**Comment by tiger2005** [comment]
草对不起自己不太会写 HTML/JS 代码 /kk
但是这个 bug 已经在修了。目前在想安全的解决发送消息这方面的方法。

**Comment by Schwarzkopf-Henkal** [comment]
剩下一个发送信息。

**Comment by Schwarzkopf-Henkal** [comment]
> 剩下一个发送信息。

噢，好像已经修好了（
